import { Project } from '@/types/portfolio';

export const PROJECTS: Project[] = [
  {
    id: 'leadpilot',
    slug: 'leadpilot',
    title: 'LeadPilot',
    tagline: 'Automated lead generation and prospect intelligence workspace.',
    year: '2025',
    role: ['Product Thinking', 'Full-Stack Engineering', 'UI/UX Design'],
    category: 'Product',
    featured: true,
    heroImage: {
      type: 'interactive',
      alt: 'LeadPilot Workspace Interface',
      aspectRatio: '16:9',
    },
    summary: 'A high-throughput lead intelligence and prospect discovery application built for fast data aggregation and clean workflow orchestration.',
    techStack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Node.js', 'AI Integration'],
    status: 'Production',
  },
  {
    id: 'tradestak',
    slug: 'tradestak',
    title: 'TradeStak',
    tagline: 'Modern trading workspace and market analytics interface.',
    year: '2025',
    role: ['UI/UX Architecture', 'Frontend Engineering'],
    category: 'Web Platform',
    featured: true,
    heroImage: {
      type: 'interactive',
      alt: 'TradeStak Market Analytics Workspace',
      aspectRatio: '16:9',
    },
    summary: 'High-density financial tracking interface designed for real-time market data visualization, portfolio analytics, and low-latency interaction.',
    techStack: ['React', 'TypeScript', 'Tailwind CSS', 'Data Visualization'],
    status: 'Production',
  },
  {
    id: 'internet-time-capsule',
    slug: 'internet-time-capsule',
    title: 'Internet Time Capsule',
    tagline: 'Digital archival experience capturing web culture moments.',
    year: '2025',
    role: ['Creative Technology', 'Interaction Design', 'Frontend'],
    category: 'AI Experiment',
    featured: true,
    heroImage: {
      type: 'interactive',
      alt: 'Internet Time Capsule Interactive Experience',
      aspectRatio: '16:9',
    },
    summary: 'An interactive web experience exploring digital memory, historical archive visualizers, and web preservation aesthetics.',
    techStack: ['Next.js', 'Motion', 'Tailwind CSS'],
    status: 'Active Prototype',
  },
  {
    id: 'athena',
    slug: 'athena',
    title: 'ATHENA',
    tagline: 'Advanced AI-driven intelligence and operational system assistant.',
    year: '2026',
    role: ['AI Engineering', 'UI/UX Design', 'System Architecture'],
    category: 'AI Experiment',
    featured: true,
    heroImage: {
      type: 'interactive',
      alt: 'ATHENA AI System Interface',
      aspectRatio: '16:9',
    },
    summary: 'Multi-modal AI assistant interface crafted for complex task synthesis, agentic workflow orchestration, and structured output formatting.',
    techStack: ['Python', 'TypeScript', 'AI Frameworks', 'Next.js'],
    status: 'Active Prototype',
  },
];