import { Project } from '@/types/portfolio';

export const PROJECTS: Project[] = [
  {
    id: 'leadpilot',
    slug: 'leadpilot',
    title: 'LeadPilot',
    tagline: 'Automated lead generation and prospect intelligence workspace.',
    year: '2025',
    role: ['Product Thinking', 'Full-Stack Engineering', 'UI/UX Design'],
    category: 'Product',
    featured: true,
    heroImage: {
      type: 'interactive',
      alt: 'LeadPilot Workspace Interface',
      aspectRatio: '16:9',
      caption: 'Interactive prospect discovery dashboard frame.',
    },
    summary: 'A high-throughput lead intelligence platform built to aggregate B2B prospect data, automate enrichment pipelines, and streamline sales outreach workflows.',
    problemStatement: 'Sales and growth teams spend hours manually searching, validating, and structuring prospect leads across fragmented databases, leading to high drop-offs and inconsistent data quality.',
    approach: 'Designed a unified workspace interface centered on real-time data aggregation, structured query filters, and automated enrichment pipelines to reduce prospect discovery time.',
    designNotes: 'Focused on high-density data tables, clean status badging, keyboard shortcuts for fast triage, and a dark editorial visual theme to reduce visual fatigue during prolonged usage.',
    engineeringNotes: 'Architected with Next.js App Router for optimal server rendering, combined with a modular Node.js data pipeline and TypeScript domain models for strict type safety.',
    techStack: ['Next.js 15', 'TypeScript', 'Tailwind CSS v4', 'Node.js', 'AI Integration'],
    deliverables: ['Product Architecture', 'UI/UX Component Library', 'Enrichment API Pipeline'],
    status: 'Production',
  },
  {
    id: 'tradestak',
    slug: 'tradestak',
    title: 'TradeStak',
    tagline: 'Modern trading workspace and market analytics interface.',
    year: '2025',
    role: ['UI/UX Architecture', 'Frontend Engineering'],
    category: 'Web Platform',
    featured: true,
    heroImage: {
      type: 'interactive',
      alt: 'TradeStak Analytics Workspace',
      aspectRatio: '16:9',
      caption: 'Real-time market analytics and financial tracking dashboard.',
    },
    summary: 'A high-density financial tracking interface designed for real-time market data visualization, portfolio analytics, and low-latency interaction.',
    problemStatement: 'Traders and financial analysts struggle with cluttered, slow-updating interfaces that lack spatial hierarchy and fail to provide fast visual feedback during volatility.',
    approach: 'Built a modular visual grid system with dark high-contrast chart primitives, customized indicators, and responsive workspace layouts for rapid market assessment.',
    designNotes: 'Employed a strict near-black palette with icy blue accents for key data trends, clear monospaced numerical typography, and subtle micro-interactions.',
    engineeringNotes: 'Optimized state management and dynamic chart rendering to eliminate unnecessary component re-renders during high-frequency data updates.',
    techStack: ['React 19', 'TypeScript', 'Tailwind CSS v4', 'Data Visualization'],
    deliverables: ['Financial Workspace Design', 'Custom Chart Components', 'State Optimization Layer'],
    status: 'Production',
  },
  {
    id: 'internet-time-capsule',
    slug: 'internet-time-capsule',
    title: 'Internet Time Capsule',
    tagline: 'Digital archival experience capturing web culture moments.',
    year: '2025',
    role: ['Creative Technology', 'Interaction Design', 'Frontend'],
    category: 'AI Experiment',
    featured: true,
    heroImage: {
      type: 'interactive',
      alt: 'Internet Time Capsule Experience',
      aspectRatio: '16:9',
      caption: 'Interactive digital archive experience.',
    },
    summary: 'An interactive web experience exploring digital memory, historical archive visualizers, and web preservation aesthetics.',
    problemStatement: 'Digital media and web culture evolve so rapidly that iconic moments, websites, and cultural milestones disappear without meaningful interactive archiving.',
    approach: 'Created a temporal visual timeline allowing visitors to explore snapshots of web history through fluid gestures, spatial typography, and archival cards.',
    designNotes: 'Blended retro web aesthetics with modern cinematic dark UI, incorporating subtle grain textures and smooth scroll-driven reveals.',
    engineeringNotes: 'Utilized Motion spring physics and CSS hardware acceleration to achieve 60fps momentum scrolling across desktop and mobile viewports.',
    techStack: ['Next.js 15', 'Motion', 'Tailwind CSS v4'],
    deliverables: ['Archival Experience Design', 'Temporal Timeline Component', 'Motion Infrastructure'],
    status: 'Active Prototype',
  },
  {
    id: 'athena',
    slug: 'athena',
    title: 'ATHENA',
    tagline: 'Advanced AI-driven intelligence and operational system assistant.',
    year: '2026',
    role: ['AI Engineering', 'UI/UX Design', 'System Architecture'],
    category: 'AI Experiment',
    featured: true,
    heroImage: {
      type: 'interactive',
      alt: 'ATHENA System Agent Control Interface',
      aspectRatio: '16:9',
      caption: 'Multi-agent AI control panel and task execution view.',
    },
    summary: 'Multi-modal AI assistant interface crafted for complex task synthesis, agentic workflow orchestration, and structured output formatting.',
    problemStatement: 'Complex AI subagent workflows often lack transparent visual control, making it difficult for users to track reasoning steps, task states, and artifact outputs.',
    approach: 'Engineered a dark technical dashboard presenting live agent lifecycle states, stream outputs, and task execution trees in a single unified interface.',
    designNotes: 'Designed technical monospaced metadata status badges, sleek glass panels, and clear spatial separation between system logs and output artifacts.',
    engineeringNotes: 'Implemented real-time event listeners and typed JSON streaming consumers for live task status synchronization.',
    techStack: ['Python', 'TypeScript', 'AI Agent Frameworks', 'Next.js 15'],
    deliverables: ['Agent Control Dashboard', 'Streaming Event Consumer', 'System Architecture Spec'],
    status: 'Active Prototype',
  },
];